const tableData = {
  'flag': true,
  'msg': '',
  'data': [
    {
      'labelCategoryId': '922',
      'labelCategoryName': 'AIA_POC',
      'labelCategoryDisplayName': 'AIA测试POC',
      'labelCategoryDes': '',
      'createUserId': '301626008',
      'creatorUserName': 'test114(test114@demo-dataphin)',
      'modifierUserId': '301626008',
      'modifierUserName': 'test114(test114@demo-dataphin)',
      'gmtCreate': '2020-09-17 15:24:24',
      'gmtModified': '2020-09-17 15:28:10',
      'labelCount': 0
    },
    {
      'labelCategoryId': '651',
      'labelCategoryName': 'baison_test',
      'labelCategoryDisplayName': 'baison_test',
      'labelCategoryDes': 'baison_test',
      'createUserId': '581914',
      'creatorUserName': 'baisheng(baisheng@demo-dataphin)',
      'modifierUserId': '581914',
      'modifierUserName': 'baisheng(baisheng@demo-dataphin)',
      'gmtCreate': '2020-05-29 14:41:15',
      'gmtModified': '2020-05-29 14:41:15',
      'labelCount': 1
    },
    {
      'labelCategoryId': '657',
      'labelCategoryName': 'gcleimu',
      'labelCategoryDisplayName': 'gcleimu',
      'labelCategoryDes': '',
      'createUserId': '315642',
      'creatorUserName': '演示默认管理(demo_default@demo-dataphin)',
      'modifierUserId': '315642',
      'modifierUserName': '演示默认管理(demo_default@demo-dataphin)',
      'gmtCreate': '2020-06-01 10:59:02',
      'gmtModified': '2020-06-01 10:59:02',
      'labelCount': 0
    },
    {
      'labelCategoryId': '188',
      'labelCategoryName': 'order_cat_yz',
      'labelCategoryDisplayName': 'order_cat_yz',
      'labelCategoryDes': '',
      'createUserId': '300095795',
      'creatorUserName': 'test006(test006@demo-dataphin)',
      'modifierUserId': '300095795',
      'modifierUserName': 'test006(test006@demo-dataphin)',
      'gmtCreate': '2019-12-18 17:54:58',
      'gmtModified': '2019-12-18 17:54:58',
      'labelCount': 2
    },
    {
      'labelCategoryId': '927',
      'labelCategoryName': 'ss_merchant',
      'labelCategoryDisplayName': 'ss_商品',
      'labelCategoryDes': '',
      'createUserId': '301175845',
      'creatorUserName': 'test093(test093@demo-dataphin)',
      'modifierUserId': '301175845',
      'modifierUserName': 'test093(test093@demo-dataphin)',
      'gmtCreate': '2020-09-18 11:54:35',
      'gmtModified': '2020-09-18 11:54:35',
      'labelCount': 2
    },
    {
      'labelCategoryId': '126',
      'labelCategoryName': 'test',
      'labelCategoryDisplayName': 'test',
      'labelCategoryDes': '',
      'createUserId': '834468',
      'creatorUserName': 'test004@demo-dataphin',
      'modifierUserId': '834468',
      'modifierUserName': 'test004@demo-dataphin',
      'gmtCreate': '2019-12-04 10:13:14',
      'gmtModified': '2019-12-04 10:13:14',
      'labelCount': 1
    },
    {
      'labelCategoryId': '691',
      'labelCategoryName': 'trade_lable',
      'labelCategoryDisplayName': '交易标签',
      'labelCategoryDes': '',
      'createUserId': '300533478',
      'creatorUserName': 'test049(test049@demo-dataphin)',
      'modifierUserId': '300533478',
      'modifierUserName': 'test049(test049@demo-dataphin)',
      'gmtCreate': '2020-06-15 18:17:30',
      'gmtModified': '2020-06-16 16:42:25',
      'labelCount': 4
    },
    {
      'labelCategoryId': '59',
      'labelCategoryName': 'other_labels',
      'labelCategoryDisplayName': '其他标签',
      'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
      'createUserId': '209252',
      'creatorUserName': 'demo_dataphin',
      'modifierUserId': '209252',
      'modifierUserName': 'demo_dataphin',
      'gmtCreate': '2019-11-19 14:37:51',
      'gmtModified': '2019-11-19 14:37:51',
      'labelCount': 52
    }
  ],
  'monitorLog': null
}

const factoryTableData = {
  'flag': true,
  'msg': '',
  'data': [
    {
      'labelId': '918',
      'name': 'item_price_favor091511',
      'displayName': '最近30天商品价格偏好0915',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-10-29 15:12:23',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_item_price_prefer',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '1092',
      'name': 'asasa',
      'displayName': 'asa',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'NOT_EXECUTE',
      'gmtModified': '2020-10-28 17:17:05',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_fdsasasd',
      'status': '6',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '1075',
      'name': 'behivor_1',
      'displayName': '访问行为偏好',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'FAILED',
      'gmtModified': '2020-10-26 16:54:48',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_behivor_1',
      'status': '7',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '1074',
      'name': 'abcd',
      'displayName': 'ABCD',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '927',
        'labelCategoryName': 'ss_merchant',
        'labelCategoryDisplayName': 'ss_商品',
        'labelCategoryDes': '',
        'createUserId': '301175845',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2020-09-18 11:54:35',
        'gmtModified': null
      },
      'executeStatus': 'NOT_EXECUTE',
      'gmtModified': '2020-10-26 14:26:57',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_abcd',
      'status': '6',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '1066',
      'name': 'prise1022',
      'displayName': '价格标签测试1022',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '691',
        'labelCategoryName': 'trade_lable',
        'labelCategoryDisplayName': '交易标签',
        'labelCategoryDes': '',
        'createUserId': '300533478',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2020-06-15 18:17:30',
        'gmtModified': null
      },
      'executeStatus': 'NOT_EXECUTE',
      'gmtModified': '2020-10-26 10:07:14',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_prise1022',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '1067',
      'name': 'good_user',
      'displayName': '偏好用户',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '691',
        'labelCategoryName': 'trade_lable',
        'labelCategoryDisplayName': '交易标签',
        'labelCategoryDes': '',
        'createUserId': '300533478',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2020-06-15 18:17:30',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-10-22 16:23:20',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_good_user',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '772',
      'name': 'customer_active',
      'displayName': '客户活跃度',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'FAILED',
      'gmtModified': '2020-10-22 15:43:25',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_customer_active11',
      'status': '6',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '1063',
      'name': 'englist',
      'displayName': '英语',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-10-21 16:01:30',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_cessss',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '919',
      'name': 'item_cate_prefer0915',
      'displayName': '最近30天商品类目偏好0915',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'FAILED',
      'gmtModified': '2020-10-19 11:15:36',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_item_cate_prefer0915',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '1048',
      'name': 'people_behavior_prefer',
      'displayName': '用户行为偏好',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'NOT_EXECUTE',
      'gmtModified': '2020-10-16 16:53:14',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_people_behavior_prefer',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '928',
      'name': 'ss_merchant',
      'displayName': 'ss_商品',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '927',
        'labelCategoryName': 'ss_merchant',
        'labelCategoryDisplayName': 'ss_商品',
        'labelCategoryDes': '',
        'createUserId': '301175845',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2020-09-18 11:54:35',
        'gmtModified': null
      },
      'executeStatus': 'NOT_EXECUTE',
      'gmtModified': '2020-09-18 12:17:47',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_ss_merchant',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '895',
      'name': 'ss_item_price_favor',
      'displayName': 'ss_最近30天商品价格偏好',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-09-10 17:12:05',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_ss_item_price_favor',
      'status': '6',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '870',
      'name': 'fc_test_02',
      'displayName': '付川的测试标签02',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'NOT_EXECUTE',
      'gmtModified': '2020-09-08 17:43:00',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_fctest02',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '862',
      'name': 'FC_TestLabel',
      'displayName': '付川的测试标签',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '691',
        'labelCategoryName': 'trade_lable',
        'labelCategoryDisplayName': '交易标签',
        'labelCategoryDes': '',
        'createUserId': '300533478',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2020-06-15 18:17:30',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-09-08 11:43:50',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_fctest',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '818',
      'name': 'ewq',
      'displayName': 'weq',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '651',
        'labelCategoryName': 'baison_test',
        'labelCategoryDisplayName': 'baison_test',
        'labelCategoryDes': 'baison_test',
        'createUserId': '581914',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2020-05-29 14:41:15',
        'gmtModified': null
      },
      'executeStatus': 'FAILED',
      'gmtModified': '2020-07-30 15:53:10',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_e',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '770',
      'name': 'user_type_tool',
      'displayName': '用户购买标签',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-07-27 16:00:40',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_user_type_tool',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '768',
      'name': 'a1',
      'displayName': 'a1',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-07-23 17:39:00',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_a1',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '760',
      'name': 'gc0723title',
      'displayName': 'gc0723标签',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-07-23 15:27:50',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_gc0723result',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '379',
      'name': 'TestTag0310',
      'displayName': '测试标签0310',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-07-16 16:03:30',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_test_tag0310',
      'status': '6',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '641',
      'name': 'baison_view',
      'displayName': '浏览类目',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-07-09 16:25:26',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_baison_view',
      'status': 'DEVELOPING',
      'publicStatus': 'NOT_PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '695',
      'name': 'pack_pay_favor',
      'displayName': '最近30天的礼包的购买偏好',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '691',
        'labelCategoryName': 'trade_lable',
        'labelCategoryDisplayName': '交易标签',
        'labelCategoryDes': '',
        'createUserId': '300533478',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2020-06-15 18:17:30',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-06-29 15:30:23',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_pay_favor_000189',
      'status': 'DEVELOPING',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '703',
      'name': 'cc',
      'displayName': 'cc',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'NOT_EXECUTE',
      'gmtModified': '2020-06-28 15:59:27',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_cc',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '457',
      'name': 'cc_user_category_pref',
      'displayName': 'cc用户类目偏好',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-06-24 16:48:00',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_cc_user_category_pref',
      'status': 'DEVELOPING',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '622',
      'name': 'aa',
      'displayName': 'ff',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-06-23 16:28:20',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_info',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '604',
      'name': 'hntest_item_cate_prefer',
      'displayName': 'hntest_最近30天商品类目偏好',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-05-13 17:16:30',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_hntest_item_cate_prefer',
      'status': 'DEVELOPING',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '603',
      'name': 'hntest_item_price_favor',
      'displayName': 'hntest_最近30天商品价格偏好',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-05-13 16:47:00',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_hntest_item_price_favor',
      'status': 'DEVELOPING',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '530',
      'name': 'item_price_favor',
      'displayName': '最近30天商品价格偏好',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-05-12 14:05:57',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_item_price_favor',
      'status': '6',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '531',
      'name': 'item_cate_prefer',
      'displayName': '最近30天商品类目偏好',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-05-12 14:05:35',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_item_cate_prefer',
      'status': '6',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '514',
      'name': 'lab1',
      'displayName': 'lab1',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'NOT_EXECUTE',
      'gmtModified': '2020-04-26 14:24:24',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_info',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '513',
      'name': 'lable1',
      'displayName': 'lable1',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'NOT_EXECUTE',
      'gmtModified': '2020-04-24 16:15:10',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_cc_order_info',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '460',
      'name': 'cc_user_brand_pref',
      'displayName': '用户品牌偏好',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-04-17 20:37:30',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_cc_user_brand_pref',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '459',
      'name': 'cc_user_brand_preference',
      'displayName': 'cc用户品牌偏好1',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-04-16 11:27:00',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_cc_user_brand_preference',
      'status': '6',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '428',
      'name': 'zm_extraction',
      'displayName': 'zm萃取',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-03-25 15:49:30',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_zm_extraction',
      'status': '6',
      'publicStatus': 'NOT_PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '419',
      'name': 'flag_use_coupon',
      'displayName': '使用优惠券',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-03-21 10:19:10',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_use_coupon',
      'status': '6',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '374',
      'name': 'test',
      'displayName': '测试标签',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '126',
        'labelCategoryName': 'test',
        'labelCategoryDisplayName': 'test',
        'labelCategoryDes': '',
        'createUserId': '834468',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-12-04 10:13:14',
        'gmtModified': null
      },
      'executeStatus': 'FAILED',
      'gmtModified': '2020-03-05 17:41:56',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_test',
      'status': '5',
      'publicStatus': 'NOT_PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '345',
      'name': 'btn_member_hw',
      'displayName': 'btn_member_hw',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-02-22 19:31:48',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_btn_member_hw',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '335',
      'name': 'issleep_hw_q1',
      'displayName': 'issleep_hw_q1',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-02-21 17:02:00',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_issleep_hw_q1',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '312',
      'name': 'item_brand_preference',
      'displayName': '商品品牌偏好_hw',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-02-21 17:01:34',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_item_brand_preference',
      'status': '6',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '331',
      'name': 'btn_pay_account',
      'displayName': 'btn_pay_account',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-02-21 13:46:40',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_btn_pay_account_hw',
      'status': '6',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '303',
      'name': 'user_login_source',
      'displayName': '用户登录来源',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-02-21 01:58:30',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_user_login_source',
      'status': 'DEVELOPING',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '320',
      'name': 'crm_order_issleep_test_hw',
      'displayName': '沉睡流失标识_hw',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-02-20 15:54:00',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_crm_order_issleep_hw_test',
      'status': 'DEVELOPING',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '296',
      'name': 'good_view_favor',
      'displayName': '商品浏览偏好',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-02-17 11:12:50',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_good_view_favor_tags',
      'status': 'DEVELOPING',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '290',
      'name': 'good_price_favor_lee',
      'displayName': '商品价格偏好_lee',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-02-14 18:58:10',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_good_price_favor_lee',
      'status': 'DEVELOPING',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '285',
      'name': 'lb_cate_prefer_yz',
      'displayName': 'lb_cate_prefer_yz',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '188',
        'labelCategoryName': 'order_cat_yz',
        'labelCategoryDisplayName': 'order_cat_yz',
        'labelCategoryDes': '',
        'createUserId': '300095795',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-12-18 17:54:58',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-02-08 16:22:00',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_lb_cate_prefer_yz',
      'status': '6',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '274',
      'name': 'goods_price_favor',
      'displayName': '商品价格偏好',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'NOT_EXECUTE',
      'gmtModified': '2020-01-19 14:14:40',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_goods_price_favor',
      'status': '6',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '273',
      'name': 'cate_favor2',
      'displayName': '商品类目偏好',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'NOT_EXECUTE',
      'gmtModified': '2020-01-16 18:24:00',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_cate_favor2',
      'status': '6',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '238',
      'name': 'zk_user_sex',
      'displayName': '自然属性',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-01-14 16:55:20',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_user_sex_zk_1d',
      'status': '6',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '149',
      'name': 'WM_Action',
      'displayName': 'WM_Action',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-01-07 17:17:25',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_WM_Action',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '230',
      'name': 'order_pay_ammount_zk',
      'displayName': '订单总金额_zk',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '59',
        'labelCategoryName': 'other_labels',
        'labelCategoryDisplayName': '其他标签',
        'labelCategoryDes': '系统默认标签类目, 不可编辑和删除',
        'createUserId': '209252',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-11-19 14:37:51',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2020-01-06 18:04:50',
      'lastRefreshStatus': 'NOT_RUNNING',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_order_pay_ammount_7d_zk',
      'status': '5',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    },
    {
      'labelId': '189',
      'name': 'lb_amount_prefer_yz',
      'displayName': 'lb_amount_prefer_yz',
      'desc': null,
      'labelCategory': {
        'labelCategoryId': '188',
        'labelCategoryName': 'order_cat_yz',
        'labelCategoryDisplayName': 'order_cat_yz',
        'labelCategoryDes': '',
        'createUserId': '300095795',
        'creatorUserName': null,
        'modifierUserId': null,
        'modifierUserName': null,
        'gmtCreate': '2019-12-18 17:54:58',
        'gmtModified': null
      },
      'executeStatus': 'SUCCESS',
      'gmtModified': '2019-12-28 12:03:40',
      'lastRefreshStatus': 'SUCCESS',
      'lastRefreshTime': null,
      'labelResultTable': 'Data_Distill_lb_amount_prefer_yz',
      'status': '6',
      'publicStatus': 'PUBLIC',
      'labelExecuteNodeId': null
    }
  ],
  'monitorLog': null
}

const manualTableData = {
  'flag': true,
  'msg': '',
  'data': [
    {
      'id': '215',
      'name': 'trajectory_count_last7day',
      'displayName': '近一周活动次数_跨区域_',
      'desc': null,
      'gmtModified': '2020-10-30 11:24:59',
      'sourceTableName': 't_dwd_people_info',
      'sourceColumnName': 'trajectory_count_last7day',
      'labelPublicStatus': 'PUBLIC',
      'labelCategoryId': '59',
      'labelCategoryDisplayName': '其他标签',
      'labelCategoryName': 'other_labels'
    },
    {
      'id': '214',
      'name': 'trajectory_count_last1day',
      'displayName': '近一天活动次数_跨区域_',
      'desc': null,
      'gmtModified': '2020-10-30 11:24:59',
      'sourceTableName': 't_dwd_people_info',
      'sourceColumnName': 'trajectory_count_last1day',
      'labelPublicStatus': 'PUBLIC',
      'labelCategoryId': '59',
      'labelCategoryDisplayName': '其他标签',
      'labelCategoryName': 'other_labels'
    },
    {
      'id': '210',
      'name': 'call_connect_time_last7day',
      'displayName': '近一周通话时长',
      'desc': null,
      'gmtModified': '2020-10-30 10:55:06',
      'sourceTableName': 't_dwd_people_info',
      'sourceColumnName': 'call_connect_time_last7day',
      'labelPublicStatus': 'PUBLIC',
      'labelCategoryId': '59',
      'labelCategoryDisplayName': '其他标签',
      'labelCategoryName': 'other_labels'
    },
    {
      'id': '209',
      'name': 'sms_connect_count_last1day',
      'displayName': '近一天短信次数',
      'desc': null,
      'gmtModified': '2020-10-29 15:07:46',
      'sourceTableName': 't_dwd_people_info',
      'sourceColumnName': 'sms_connect_count_last1day',
      'labelPublicStatus': 'PUBLIC',
      'labelCategoryId': '59',
      'labelCategoryDisplayName': '其他标签',
      'labelCategoryName': 'other_labels'
    },
    {
      'id': '208',
      'name': 'call_connect_time_last1day',
      'displayName': '近一天通话时长',
      'desc': null,
      'gmtModified': '2020-10-29 15:07:46',
      'sourceTableName': 't_dwd_people_info',
      'sourceColumnName': 'call_connect_time_last1day',
      'labelPublicStatus': 'PUBLIC',
      'labelCategoryId': '59',
      'labelCategoryDisplayName': '其他标签',
      'labelCategoryName': 'other_labels'
    },
    {
      'id': '203',
      'name': 'device_type',
      'displayName': '设备类型',
      'desc': null,
      'gmtModified': '2020-10-19 11:11:45',
      'sourceTableName': 't_dwd_devicetype_os_di',
      'sourceColumnName': 'device_type',
      'labelPublicStatus': 'PUBLIC',
      'labelCategoryId': '59',
      'labelCategoryDisplayName': '其他标签',
      'labelCategoryName': 'other_labels'
    },
    {
      'id': '86',
      'name': 'prefer',
      'displayName': 'prefer',
      'desc': '',
      'gmtModified': '2020-10-16 10:51:05',
      'sourceTableName': 'data_distill_pay_favor_000189',
      'sourceColumnName': 'prefer',
      'labelPublicStatus': 'PUBLIC',
      'labelCategoryId': '59',
      'labelCategoryDisplayName': '其他标签',
      'labelCategoryName': 'other_labels'
    },
    {
      'id': '43',
      'name': 'behavior_count',
      'displayName': 'behavior_count',
      'desc': null,
      'gmtModified': '2020-03-05 18:19:34',
      'sourceTableName': 'data_distill_good_price_favor_lee',
      'sourceColumnName': 'behavior_count',
      'labelPublicStatus': 'PUBLIC',
      'labelCategoryId': '59',
      'labelCategoryDisplayName': '其他标签',
      'labelCategoryName': 'other_labels'
    }
  ],
  'monitorLog': null
}

const treeData = {
  'flag': true,
  'msg': '',
  'data': [
    {
      'id': '450000199608265715',
      'name': '精使务众联照花数',
      'code': 'ersqykscerkeruspvslcqofs',
      'type': 1,
      'oper_user': '王刚',
      'updater': '刘丽',
      'oper_time': '1977-06-21 23:15:24',
      'fileType': 1
    },
    {
      'id': '610000201703256358',
      'name': '世发期技它情成',
      'code': 'clthqcbjnivjjfertsswunbdpkjvmdujittfihwmpqk',
      'type': 1,
      'oper_user': '侯敏',
      'updater': '谭艳',
      'oper_time': '1973-01-20 19:00:28',
      'fileType': 2
    },
    {
      'id': '440000198303047614',
      'name': '定手我技六容太',
      'code': 'bfwdnkkvfamgvpgblhmnimrwgvurrmmqiwiskhvbjqkhkbjfqeksyxbd',
      'type': 1,
      'oper_user': '任勇',
      'updater': '常静',
      'oper_time': '1978-06-09 19:05:55'
    },
    {
      'id': '140000200102066930',
      'name': '收龙民单说农复',
      'code': 'ddvsyqgghvrfezdyllnhmisccjtbw',
      'type': 1,
      'oper_user': '锺芳',
      'updater': '高秀兰',
      'oper_time': '1990-08-28 22:26:40'
    },
    {
      'id': '640000199701309124',
      'name': '新于压达此期至样',
      'code': 'yegdkclcmgqlfijugjdaxoinoxiyclq',
      'type': 1,
      'oper_user': '徐刚',
      'updater': '乔桂英',
      'oper_time': '2003-01-03 23:16:50'
    },
    {
      'id': '150000198107024731',
      'name': '件容采话美意制原',
      'code': 'ogdulgdsubhiniopyqzlsxzmn',
      'type': 1,
      'oper_user': '姚明',
      'updater': '邓超',
      'oper_time': '1994-10-21 02:32:30'
    },
    {
      'id': '430000197609121905',
      'name': '问军始只设心还价革',
      'code': 'etmpkeivgfwxmudlesmuewgeyppvscvyyervzbnrtge',
      'type': 1,
      'oper_user': '金强',
      'updater': '梁杰',
      'oper_time': '1976-12-15 19:24:53'
    },
    {
      'id': '430000201404250921',
      'name': '如议热就先委老',
      'code': 'lgmulxldipdikswuxplgodyuvplrkvjhnvqslvgktxuvbjk',
      'type': 1,
      'oper_user': '李杰',
      'updater': '李涛',
      'oper_time': '1998-02-04 01:16:27'
    },
    {
      'id': '990000201107252807',
      'name': '或变价南和又',
      'code': 'eqqhhoqpqvfnauxxdhdwxohcxqd',
      'type': 1,
      'oper_user': '石洋',
      'updater': '胡桂英',
      'oper_time': '1991-02-18 21:13:14'
    },
    {
      'id': '420000197207023243',
      'name': '型员土头步合',
      'code': 'hjjgbjevvigtgxtpwnngwdzbbuyowjgenwnpp',
      'type': 1,
      'oper_user': '夏磊',
      'updater': '丁秀兰',
      'oper_time': '1978-04-12 16:22:35'
    },
    {
      'id': '350000199604159743',
      'name': '高场展见较许周业习',
      'code': 'mxsoddfurpjrlupossgsncehojblmap',
      'type': 1,
      'oper_user': '姜芳',
      'updater': '李秀英',
      'oper_time': '2020-05-04 23:44:39'
    },
    {
      'id': '230000197307034892',
      'name': '易精电比形内',
      'code': 'ywmhfsepywkoemxrczjrjyspnpddvlbthkhbbkvllondcxxscuxtnbn',
      'type': 1,
      'oper_user': '邵秀英',
      'updater': '顾平',
      'oper_time': '1979-02-08 07:18:19'
    },
    {
      'id': '370000201001206647',
      'name': '经至青算计达清农',
      'code': 'bjhmfxdsghnqbufgjuvfgpsexdku',
      'type': 1,
      'oper_user': '金强',
      'updater': '范娜',
      'oper_time': '1998-04-07 20:53:57'
    },
    {
      'id': '63000020050214771X',
      'name': '切决展所属战何',
      'code': 'vpkmfytezsokaqcjvdzrkydyh',
      'type': 1,
      'oper_user': '段娟',
      'updater': '戴艳',
      'oper_time': '1972-06-07 05:06:34'
    },
    {
      'id': '310000199404278759',
      'name': '装作写火目它平',
      'code': 'kvjplfzfxcmwmuqiimhhdrgfgmehofdvm',
      'type': 1,
      'oper_user': '顾洋',
      'updater': '石强',
      'oper_time': '2014-01-22 21:15:18'
    },
    {
      'id': '620000198605236465',
      'name': '强温市准天美机自约',
      'code': 'lksftfvnquujkicnkahjiktepqt',
      'type': 1,
      'oper_user': '邓平',
      'updater': '姚洋',
      'oper_time': '1988-10-02 17:24:07'
    },
    {
      'id': '630000201611248311',
      'name': '说而已空界美',
      'code': 'uiggglwqyjzcyiglctnyktbwvjkqmcrjuqgdakmzoyiittqoky',
      'type': 1,
      'oper_user': '杜桂英',
      'updater': '苏洋',
      'oper_time': '2020-08-27 00:01:55'
    }
  ]
}

export function getTreeData() {
  return new Promise((resolve, reject) => {
    let data = treeData
    setTimeout(() => {
      resolve(data)
    }, 1500)
  })
}

export function getTableData() {
  return new Promise((resolve, reject) => {
    let data = tableData
    setTimeout(() => {
      resolve(data)
    }, 1500)
  })
}

export function getFactoryTableData() {
  return new Promise((resolve, reject) => {
    let data = factoryTableData
    setTimeout(() => {
      resolve(data)
    }, 1500)
  })
}

export function getManualTableData() {
  return new Promise((resolve, reject) => {
    let data = manualTableData
    setTimeout(() => {
      resolve(data)
    }, 1500)
  })
}
